class AddColumnsToAttempts < ActiveRecord::Migration[6.0]
  def change
    add_column :attempts, :albania, :boolean
    add_column :attempts, :andorra, :boolean
    add_column :attempts, :austria, :boolean
    add_column :attempts, :belarus, :boolean
    add_column :attempts, :belgium, :boolean
    add_column :attempts, :bosnia, :boolean
    add_column :attempts, :bulgaria, :boolean
    add_column :attempts, :croatia, :boolean    
    add_column :attempts, :cyprus, :boolean
    add_column :attempts, :czechia, :boolean
    add_column :attempts, :denmark, :boolean
    add_column :attempts, :estonia, :boolean
    add_column :attempts, :finland, :boolean    
    add_column :attempts, :france, :boolean
    add_column :attempts, :germany, :boolean
    add_column :attempts, :greece, :boolean
    add_column :attempts, :hungary, :boolean    
    add_column :attempts, :iceland, :boolean
    add_column :attempts, :ireland, :boolean
    add_column :attempts, :italy, :boolean
    add_column :attempts, :kosovo, :boolean
    add_column :attempts, :latvia, :boolean
    add_column :attempts, :liechtenstein, :boolean
    add_column :attempts, :lithuania, :boolean
    add_column :attempts, :luxembourg, :boolean    
    add_column :attempts, :malta, :boolean
    add_column :attempts, :moldova, :boolean
    add_column :attempts, :monaco, :boolean
    add_column :attempts, :montenegro, :boolean
    add_column :attempts, :netherlands, :boolean    
    add_column :attempts, :north_macedonia, :boolean
    add_column :attempts, :norway, :boolean
    add_column :attempts, :poland, :boolean
    add_column :attempts, :portugal, :boolean
    add_column :attempts, :romania, :boolean    
    add_column :attempts, :russia, :boolean
    add_column :attempts, :san_marino, :boolean
    add_column :attempts, :serbia, :boolean
    add_column :attempts, :slovakia, :boolean
    add_column :attempts, :slovenia, :boolean    
    add_column :attempts, :spain, :boolean
    add_column :attempts, :sweden, :boolean
    add_column :attempts, :switzerland, :boolean
    add_column :attempts, :turkey, :boolean
    add_column :attempts, :ukraine, :boolean
    add_column :attempts, :united_kingdom, :boolean
    add_column :attempts, :vatican_city, :boolean
  end
end
